### ISSUE TITLE
When to release the code?

### ISSUE THREAD

**Issue by Cemm23333** [Chen-Yang-Liu/PromptCC#1]
Good job,I am very interested in change caption task and your job promptcc.And I want to ask when to release the code

**Comment by Chen-Yang-Liu** [comment]
> Good job,I am very interested in change caption task and your job promptcc.And I want to ask when to release the code

Thank you for your interest. We will release the code as soon as possible.

**Comment by Chen-Yang-Liu** [comment]
> Good job,I am very interested in change caption task and your job promptcc.And I want to ask when to release the code

Thank you for your interest. We will release the code as soon as possible in the next few days.
