### ISSUE TITLE
CLIP features

### ISSUE THREAD

**Issue by Aki-Tomoya** [Chen-Yang-Liu/PromptCC#2]
Nice work!没想到大模型已经开始冲击RSICC了。作者可否将抽取的CLIP特征公开呢？这将会对此领域的发展做出相当大的贡献。

**Comment by Chen-Yang-Liu** [comment]
> Nice work!没想到大模型已经开始冲击RSICC了。作者可否将抽取的CLIP特征公开呢？这将会对此领域的发展做出相当大的贡献。

感谢您的关注，我们已经将论文的代码和数据公开，欢迎您尝试~

**Comment by Aki-Tomoya** [comment]
感谢您的回复！还有个问题想请教下您。根据您的readme，我使用create_input_files.py对图片进行ViT-B/32特征抽取，并成功得到了几个pkl文件。但是，我并没有发现参数“--clip_model_type”在代码中有到使用。我将参数更改为RN50x4也会得到相同的输出。请问您的特征提取过程是如何使用不同模型抽取图像特征的？

**Comment by Chen-Yang-Liu** [comment]
> 感谢您的回复！还有个问题想请教下您。根据您的readme，我使用create_input_files.py对图片进行ViT-B/32特征抽取，并成功得到了几个pkl文件。但是，我并没有发现参数“--clip_model_type”在代码中有到使用。我将参数更改为RN50x4也会得到相同的输出。请问您的特征提取过程是如何使用不同模型抽取图像特征的？

事实上，create_input_files.py并非是使用CLIP特征抽取，仅仅是保存了读取的图像值。关于CLIP提取图像特征的代码您可以在datasets.py中找到“A = self.preprocess(Image.fromarray(ori_img_list[0])).unsqueeze(0)
            B = self.preprocess(Image.fromarray(ori_img_list[1])).unsqueeze(0)”

**Comment by Aki-Tomoya** [comment]
感谢您的回复！我会去再仔细看一遍相关代码，祝您工作顺利。
